modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="totemfactory"
version="1.2-OG1.0m-Forge_1.21.1"
displayName="Create: Totem Factory"
displayURL="https://modrinth.com/mod/create-totem-factory-revived"
credits=""
authors="OG: MarcosJoestar & jargames99\nPORT: JustMili"

[[dependencies.totemfactory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.totemfactory]]
    modId="create"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.totemfactory]]
    modId="create_enchantment_industry"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"


