modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="totemfactory"
version="1.3-OG1.0m"
displayName="Create: Totem Factory"
displayURL="https://modrinth.com/mod/create-totem-factory-revived"
credits=""
authors="\n§7OG: MarcosJoestar & jargames99\n§5PORT: Mystic Creations Team"
description="The industrial revolution has come to Minecraft, and with it, new knowledge and discoveries both in the field of science and magic."

[[dependencies.totemfactory]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.totemfactory]]
modId="create"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.totemfactory]]
modId="create_enchantment_industry"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"


